"""Versioned, immutable foundations for Mighty Mouse v2 state.

Re-exports symbols from records, store, promotion, and engine sub-modules
to preserve backward compatibility while exposing the deep PolicyEngine.
"""

from __future__ import annotations

from .engine import PolicyEngine, status_document
from .promotion import PromotionController
from .records import (
    Candidate,
    Champion,
    Eligibility,
    EligibleSuccessor,
    EvaluationOutcome,
    EvaluationOutcomeKind,
    EvidenceBundle,
    ExecutionProfile,
    Experiment,
    ExperimentDecision,
    ExperimentOutcome,
    FreshHoldout,
    Generation,
    HybridHandoff,
    Mode,
    ModelIdentity,
    Pin,
    Policy,
    PolicySelection,
    Preview,
    Promotion,
    PromotionNotice,
    RecordValue,
    Restriction,
    Rollback,
    RoutingDecision,
    Scope,
    Signal,
    StoredRecord,
    TaskCategory,
    _RECOVERY_REASONS,
    _REQUIRED_PROMOTION_GATES,
    _SIGNAL_DIGEST,
    _SIGNAL_ENVIRONMENT_VALUES,
    _SIGNAL_EXECUTION_PROFILE,
    _SIGNAL_FIXED_EXECUTION_PROFILES,
    _SIGNAL_IDENTIFIER,
    _SIGNAL_MODEL_CLASSES,
    _SIGNAL_REPOSITORY,
    _candidate,
    _immutable_record_identity,
    _record_from_value,
    _record_type,
    _scope_from_document,
    _to_json_value,
    resolve_execution_profile,
    resolve_model_identity,
    validate_protected_task_categories,
)
from .store import ImmutableStateStore

__all__ = [
    "Mode",
    "TaskCategory",
    "ExperimentOutcome",
    "EvaluationOutcomeKind",
    "ExperimentDecision",
    "Scope",
    "Policy",
    "Candidate",
    "Champion",
    "EligibleSuccessor",
    "Eligibility",
    "Promotion",
    "ModelIdentity",
    "ExecutionProfile",
    "Signal",
    "HybridHandoff",
    "EvidenceBundle",
    "FreshHoldout",
    "Experiment",
    "Generation",
    "Restriction",
    "Pin",
    "Preview",
    "Rollback",
    "RoutingDecision",
    "EvaluationOutcome",
    "StoredRecord",
    "PolicySelection",
    "PromotionNotice",
    "RecordValue",
    "ImmutableStateStore",
    "PromotionController",
    "PolicyEngine",
    "validate_protected_task_categories",
    "_record_type",
    "_immutable_record_identity",
    "_to_json_value",
    "_scope_from_document",
    "_candidate",
    "_record_from_value",
    "resolve_execution_profile",
    "status_document",
    "resolve_model_identity",
]
